### ISSUE TITLE
Error at launch. connect.static() doesn't exists anymore

### ISSUE THREAD

**Issue by jonalbertini** [ofavre/ReTouchPad#6]
Hi, it seems that the connect package has made some changes in the latest 3.x version of their code base, moving the static middleware to it's own package.

you need to update some changes on your code if you don't want to force users to use the old 2.x.x connect package. it's just few changes: 

Replace [Line 4](https://github.com/ofavre/ReTouchPad/blob/master/server.js#L4) by :

``` javascript
var connect = require("connect"),
    serveStatic = require('serve-static');
```

and [Line 25](https://github.com/ofavre/ReTouchPad/blob/master/server.js#L25) by :

``` javascript
var webserver = connect()
  .use(serveStatic('www'))
  .listen(config.web_port);
```

It seems to work fine...
Good job by the way !

**Comment by ofavre** [comment]
Thanks for reporting ! ;-)
